export const OPEN_CLOSE_SELECT = 'OPEN_CLOSE_SELECT';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const SELECT_DEGREES = 'SELECT_DEGREES';
export const CHANGE_BG = 'CHANGE_BG';
export const REQUEST_DATA = 'REQUEST_DATA';
export const SET_GEOCODING_INFO = 'SET_GEOCODING_INFO';
export const SET_WEATHER_INFO = 'SET_WEATHER_INFO'