const iconCodes = {
    t01d: 'assets/images/weather/thunder.svg',
    t02d: 'assets/images/weather/thunder.svg',
    t03d: 'assets/images/weather/thunder.svg',
    t04d: 'assets/images/weather/thunder.svg',
    t05d: 'assets/images/weather/thunder.svg',
    d01d: 'assets/images/weather/snowy-4.svg',
    d02d: 'assets/images/weather/snowy-5.svg',
    d03d: 'assets/images/weather/snowy-6.svg',
    r01d: 'assets/images/weather/rainy-4.svg',
    r02d: 'assets/images/weather/rainy-5.svg',
    r03d: 'assets/images/weather/rainy-6.svg',
    f01d: 'assets/images/weather/rainy-7.svg',
    r04d: 'assets/images/weather/rainy-4.svg',
    r05d: 'assets/images/weather/rainy-1.svg',
    r06d: 'assets/images/weather/rainy-6.svg',
    s01d: 'assets/images/weather/snowy-1.svg',
    s02d: 'assets/images/weather/snowy-5.svg',
    s03d: 'assets/images/weather/snowy-6.svg',
    s04d: 'assets/images/weather/rainy-7.svg',
    s05d: 'assets/images/weather/rainy-7.svg',
    s06d: 'assets/images/weather/rainy-7.svg',
    a01d: 'assets/images/weather/cloudy.svg',
    a02d: 'assets/images/weather/cloudy.svg',
    a03d: 'assets/images/weather/cloudy.svg',
    a04d: 'assets/images/weather/cloudy.svg',
    a05d: 'assets/images/weather/cloudy.svg',
    a06d: 'assets/images/weather/cloudy.svg',
    c01d: 'assets/images/weather/day.svg',
    c02d: 'assets/images/weather/cloudy-day-1.svg',
    c03d: 'assets/images/weather/cloudy-day-3.svg',
    c04d: 'assets/images/weather/cloudy.svg',
    u00d: 'assets/images/weather/rainy-7.svg',
}

export default iconCodes;